CODIGO SEGMENT PUBLIC 'CODE'
ASSUME CS:CODIGO, DS:CODIGO, ES:CODIGO, SS:PILA

Empieza:
        Mov Ax,4c00h
        Int 21h
CODIGO ENDS

PILA SEGMENT PARA STACK 'STACK'
        DW 64 DUP (?)
PILA ENDS
END Empieza
